name: AQI Logger

on:
  schedule:
    - cron: '0 * * * *'  # Every hour (UTC time)
  workflow_dispatch:      # Allow manual run

jobs:
  run-logger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AQI Logger
        run: python logger.py

      - name: Commit updated files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add output/
          git commit -m "🔄 Update AQI logs"
          git push
        continue-on-error: true  # Avoid failing if no changes
