name: Hourly AQI Logger

on:
  schedule:
    - cron: '0 * * * *'   # every hour at minute 0

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Run logger
        run: python logger.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add output/data.json output/data.csv
          git commit -m "Hourly update $(date -u +'%Y-%m-%dT%H:%MZ')" || echo "No changes"
          git push

